import { BACKEND } from "@/constants";
import { NextResponse } from "next/server";

export async function GET() {
  // Fetch coordinator info server-side — bake it into the generated script.
  let coordinatorMultiaddr = "<COORDINATOR_MULTIADDR>";
  try {
    const res = await fetch(BACKEND.BOOTSTRAP.RUNTIME, {
      next: { revalidate: 60 },
    });
    if (res.ok) {
      const data = await res.json();
      const addrs: string[] = data.advertised_multiaddrs ?? [];
      const publicAddr =
        addrs.find(
          (a) => !a.includes("127.0.0.1") && !a.includes("/ip4/0.0.0.0")
        ) ??
        addrs[0] ??
        null;
      const peerId: string | null = data.host_peer_id ?? null;
      if (publicAddr && peerId) {
        coordinatorMultiaddr =
          publicAddr.replace(/\/p2p\/[^/]+$/, "") + `/p2p/${peerId}`;
      }
    }
  } catch {
    // Fall back to placeholder — the script will still work, user just fills it in.
  }

  const script = generateLauncherScript(coordinatorMultiaddr);

  return new NextResponse(script, {
    headers: {
      "Content-Type": "text/x-sh; charset=utf-8",
      "Content-Disposition": 'attachment; filename="start-node.sh"',
    },
  });
}

function generateLauncherScript(coordinatorMultiaddr: string): string {
  const placeholder = coordinatorMultiaddr === "<COORDINATOR_MULTIADDR>";
  return `#!/usr/bin/env bash
# QB2 Node Launcher  —  auto-generated by the QB2 operator console
# Coordinator: ${coordinatorMultiaddr}
#
# Usage:
#   bash start-node.sh [--label my-node] [--port 4020]
#
# Requirements: python3 (3.10+), pip3

set -euo pipefail

COORDINATOR="${coordinatorMultiaddr}"
NODE_LABEL=""
NODE_PORT="4020"
EXTRA_ARGS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --label) NODE_LABEL="$2"; shift 2 ;;
    --port)  NODE_PORT="$2";  shift 2 ;;
    --advertise-addr) EXTRA_ARGS="$EXTRA_ARGS --advertise-addr $2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--label NAME] [--port PORT] [--advertise-addr MULTIADDR]"
      exit 0 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

GREEN=$(tput setaf 2 2>/dev/null || echo "")
BOLD=$(tput bold   2>/dev/null || echo "")
RESET=$(tput sgr0  2>/dev/null || echo "")
info() { echo "\${GREEN}[QB2]\${RESET} $*"; }

echo ""
echo "\${BOLD}QB2 Node Launcher\${RESET}"
echo "  Coordinator: $COORDINATOR"
echo ""

# 1. Python check
if ! command -v python3 &>/dev/null; then
  echo "ERROR: python3 not found. Install Python 3.10+ and re-run." >&2; exit 1
fi
python3 -c "import sys; sys.exit(0 if sys.version_info>=(3,10) else 1)" || {
  echo "ERROR: Python 3.10+ required." >&2; exit 1
}
info "Python OK"

# 2. Dependencies
info "Installing dependencies…"
pip3 install --quiet py-libp2p qiskit qiskit-aer pydantic
info "Dependencies ready"

# 3. Download node script
SCRIPT="node-starter-template.py"
if [[ ! -f "\$SCRIPT" ]]; then
  info "Downloading \$SCRIPT…"
  curl -fsSL "$(placeholder ? "http://localhost:3000" : "")/api/network/node-script" -o "\$SCRIPT"
fi
info "Script ready"

# 4. Label prompt if not supplied
if [[ -z "\$NODE_LABEL" ]]; then
  DEFAULT=\$(hostname 2>/dev/null || echo "my-node")
  read -r -p "Node label [\$DEFAULT]: " NODE_LABEL
  NODE_LABEL="\${NODE_LABEL:-\$DEFAULT}"
fi

${placeholder ? `# NOTE: coordinator multiaddr was not detected automatically.
# Edit the COORDINATOR variable at the top of this script before running.
if [[ "$COORDINATOR" == "<COORDINATOR_MULTIADDR>" ]]; then
  echo ""
  echo "WARN: Coordinator multiaddr was not auto-detected."
  read -r -p "Enter coordinator multiaddr: " COORDINATOR
  [[ -z "$COORDINATOR" ]] && { echo "ERROR: No multiaddr provided."; exit 1; }
fi
` : ""}
# 5. Launch
info "Starting node (label=\$NODE_LABEL, port=\$NODE_PORT)…"
echo ""
# shellcheck disable=SC2086
exec python3 "\$SCRIPT" \\
  --coordinator "\$COORDINATOR" \\
  --label "\$NODE_LABEL" \\
  --port "\$NODE_PORT" \\
  \$EXTRA_ARGS
`;
}
